### ISSUE TITLE
chrome should be resized to show carousel slides

### ISSUE THREAD

**Issue by engmagdy87** [brainhubeu/react-carousel#475]
chrome should be resized to show carousel slides as it was initially not appear
BrainhubCarousel__track and its child css classes width is zero till resize
![Peek 2020-05-12 19-46](https://user-images.githubusercontent.com/8473421/81727662-a0f40b00-9489-11ea-9664-f99cb4f2fac6.gif)

**Environment**
-  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 133.97 MB / 3.75 GB
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0
  npmPackages:
    @brainhubeu/react-carousel: ^1.13.46 => 1.13.46 

- desktop
- Chrome

and this is the code

```js
<Carousel
          value={activeSlideId}
          onChange={setActiveSlideId}
          infinite
          autoPlay={4000}
          animationSpeed={1000}
          arrows={false}
          clickToChange
          centered
        >
          {HomeData.map((slide) => (
                  <HomeSlide key={slide.id} content={slide} />
          ))}
        </Carousel>
```

**Comment by piotr-s-brainhub** [comment]
@engmagdy87 

Thanks for this issue but I don't understand.

Do you mean the Chrome browser should be automatically resized by the carousel?
Client JavaScript engines offer `window.resizeTo` but it doesn't work in modern browsers (I just checked in Chrome and Firefox) and even if it worked, IMO it's not a good idea.

Could you write the reproduction steps and how it should work according to you?

**Comment by engmagdy87** [comment]
@piotr-s-brainhub as u see in gif, when app start, I cannot see the carousel but when I resize viewport by resize devTools, the carousel appear
when I inspect the carousel , I found css class BrainhubCarousel__track and its childs width is zero till resize it
this is the code
I have HomeData with is exported object with images
```js
<Carousel
          value={activeSlideId}
          onChange={setActiveSlideId}
          infinite
          autoPlay={4000}
          animationSpeed={1000}
          arrows={false}
          clickToChange
          centered
        >
          {HomeData.map((slide) => (
                  <HomeSlide key={slide.id} content={slide} />
          ))}
        </Carousel>
```

**Comment by piotr-s-brainhub** [comment]
@engmagdy87 

could you provide all the variables so I could reproduce it?

**Comment by engmagdy87** [comment]
```jsx
import React, { useState, useEffect } from 'react';
import Carousel, { Dots } from '@brainhubeu/react-carousel';
import HomeData from '../../../assets/data/home.js';
import '@brainhubeu/react-carousel/lib/style.css';
import '../../../assets/styles/components/home/slider.scss';
const HomeSlide = React.lazy(() => import('./HomeSlide'));

export default function HomeSlider() {
  const [activeSlideId, setActiveSlideId] = useState(0);
  const [isCarouselRendered, setIsCarouselRendered] = useState(false);
  const thumbnails = new Array(HomeData.length).fill(
    <div
      style={{ width: '30px', height: '2px', backgroundColor: 'white' }}
    ></div>
  );
  const renderCarousel = () => {
    if (isCarouselRendered)
      return (
        <Carousel
          value={activeSlideId}
          onChange={setActiveSlideId}
          infinite
          autoPlay={4000}
          animationSpeed={1000}
          arrows={false}
          clickToChange
          centered
        >
          {HomeData.map((slide) => (
    <HomeSlide key={slide.id} content={slide} />
           ))}
        </Carousel>
      );
  };

  return (
    <div className="home-slider-wrapper">
      {renderCarousel()}
      <Dots
        thumbnails={thumbnails}
        value={activeSlideId}
        onChange={setActiveSlideId}
        number={HomeData.length}
      />
    </div>
  );
}

```

**Comment by piotr-s-brainhub** [comment]
@engmagdy87 

I need also this `HomeData`.

`../../../assets/styles/components/home/slider.scss` could be also needed

**Comment by engmagdy87** [comment]
**HomeData**
```js
const Image1 = require("../../assets/images/home/1.png")
const Image2 = require("../../assets/images/home/2.png")
const Image3 = require("../../assets/images/home/3.png")

export default [
  {
    "id": 0,
    "body": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    "actions": [
      {
        "text": "read more at about us",
        "url": ""
      }
    ],
    "image": Image1
  },
  {
    "id": 1,
    "body": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    "actions": [
      {
        "text": "read more at our approach",
        "url": ""
      }
    ],
    "image":Image2
  },
  {
    "id": 2,
    "body": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    "actions": [
      {
        "text": "read more at our approach",
        "url": ""
      },
      {
        "text": "read more at news / events",
        "url": ""
      }
    ],
    "image": Image3
  }
]
```

**Comment by engmagdy87** [comment]
**slide.scss**

```scss
@import '../../variables.scss';
@import '../../mixins.scss';

.home-slide-wrapper {
  height: calc(100vh - #{$header-height} - #{$footer-height});
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
  @include is-mobile {
    height: calc(100vh - #{$header-height-mobile} - #{$footer-height-mobile});
  }
  h1 {
    padding-top: 10%;
    padding-left: 10%;
    width: 60%;
    font-size: 2.5rem;
    line-height: 70px;
    margin-bottom: 50px;
    text-align: justify;
    font-weight: lighter;
    @include is-mobile {
      margin-bottom: 30px;
      line-height: 35px;
      font-size: 1.4rem;
      width: 80%;
      text-align: left;
    }
    @media (max-height: 680px) {
      padding-top: 2%;
      font-size: 2rem;
      line-height: 40px;
    }
  }
  div {
    padding-left: 10%;
    padding-bottom: 40px;
    text-transform: uppercase;
    text-decoration: underline;
    @include is-mobile {
      padding-bottom: 25px;
      font-size: 0.8rem;
    }
    a {
      color: white;
    }
  }
}
```
